patches:
  jenkins.yaml:
  - op: remove
    path: /jenkins/remotingSecurity
  - op: remove
    path: /jenkins/slaveAgentPort

credentials:
  jenkins.yaml: {}
  items.yaml: {}

splits:
  items: {}
  jcasc: {}
