services:
  bundleutils:
    # Find the latest version with:
    # - docker pull ghcr.io/tsmp-falcon-platform/ci-bundle-utils
    # - docker inspect ghcr.io/tsmp-falcon-platform/ci-bundle-utils | grep "org.opencontainers.image.version"
    image: ${BUNDLEUTILS_IMAGE:-ghcr.io/tsmp-falcon-platform/ci-bundle-utils}
    # run with UID and GID of the current user
    user: "${UID:-1000}:${GID:-1000}"
    network_mode: ${NETWORK_MODE:-host}
    environment:
      - BUNDLEUTILS_USERNAME=${BUNDLEUTILS_USERNAME:-}
      - BUNDLEUTILS_PASSWORD=${BUNDLEUTILS_PASSWORD:-}
      - CASC_VALIDATION_LICENSE_KEY=${CASC_VALIDATION_LICENSE_KEY:-}
      - CASC_VALIDATION_LICENSE_CERT=${CASC_VALIDATION_LICENSE_CERT:-}
      - CASC_VALIDATION_LICENSE_KEY_B64=${CASC_VALIDATION_LICENSE_KEY_B64:-}
      - CASC_VALIDATION_LICENSE_CERT_B64=${CASC_VALIDATION_LICENSE_CERT_B64:-}
    volumes:
        # set a custom workspace directory if needed
      - ${BUNDLES_WORKSPACE:-.}:/workspace
      - bundleutils-cache:/opt/bundleutils/.cache
    working_dir: ${BUNDLES_WORKSPACE:-/opt/bundleutils/work}
    entrypoint: ["/bin/sleep", "infinity"]

  # This service is used to build the image in development mode
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: never
    image: bundleutils:dev
    entrypoint: ["sh", "-c", "echo This service is used to build the image and will not be started by default"]

volumes:
  bundleutils-cache: {}
