apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sshSecret.name }}-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "bundleutils.name" . }}
    helm.sh/chart: {{ include "bundleutils.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  privateKey: {{ .Values.sshSecret.privateKey | b64enc }}
  config: {{ .Values.sshSecret.config | b64enc }}
  known_hosts: {{ .Values.sshSecret.known_hosts | b64enc }}
